[workspace]

members = [
    "packages/*",
    "contracts/liquidity_hub/pool-network/terraswap_factory",
    "contracts/liquidity_hub/pool-network/terraswap_pair",
    "contracts/liquidity_hub/pool-network/terraswap_router",
    "contracts/liquidity_hub/pool-network/terraswap_token",
    "contracts/liquidity_hub/fee_collector",
    "contracts/liquidity_hub/vault-network/*",
]

[workspace.package]
edition = "2021"
homepage = "https://whitewhale.money"
license = "MIT"
repository = "https://github.com/White-Whale-Defi-Platform/migaloo-core"
publish = false

[workspace.dependencies]
cosmwasm-schema = "1.1.4"
cosmwasm-std = { version = "1.1.4", features = ["iterator"] }
cw2 = "0.15.1"
cw20 = "0.15.1"
cw20-base = { version = "0.15.1", features = ["library"] }
cw-storage-plus = "0.15.1"
protobuf = { version = "3.1.0", features = ["with-bytes"] }
schemars = "0.8.3"
semver = "1.0.12"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
pool-network = { path = "./packages/pool-network" }
thiserror = "1.0.21"
vault-network = { path = "./packages/vault-network" }
white-whale = { path = "./packages/white-whale" }

[workspace.metadata.dylint]
libraries = [{ git = "https://github.com/0xFable/cw-lint" }]

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
