[package]
name = "vault-network"
version = "1.0.1"
edition.workspace = true
authors = ["kaimen-sano <kaimen_sano@protonmail.com>"]
description = "Messages for the Vault Network"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://whitewhale.money"

[dependencies]
cosmwasm-std.workspace = true
pool-network.workspace = true
serde.workspace = true
schemars.workspace = true
white-whale.workspace = true
cosmwasm-schema.workspace = true
